### ISSUE TITLE
[Bug]: error while moving queries to the new class

### ISSUE THREAD

**Issue by MMacphee19** [euan-maccoll/sem_group1_cw#12]
### Contact Details

40609758@live.napier.ac.uk

### What happened?

When trying to move queries to a new class we received the following error.

### Version

1.0.2 (Default)

### Relevant log output

```shell
All cities in the world and their population (From largest to smallest)
Cannot invoke "java.sql.Connection.createStatement()" because "this.com" is null
Failed to get city details
No cities
Exception in thread "main" java.long.NullPointerException: Cannot invoke "java.util.
at com.napier.sem.App.main(App.java.44)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by euan-maccoll** [comment]
maybe your trying to call the wrong method because the con method comes inside the connection method?
