### ISSUE TITLE
query showing 7 billion?

### ISSUE THREAD

**Issue by euan-maccoll** [euan-maccoll/sem_group1_cw#14]
### Contact Details

40594128@live.napier.ac.uk

### What happened?

i was running a query and the output is 7779214000 (7 billion) i think it's adding the populations together? the output should be 309632000 (309 million).

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MMacphee19** [comment]
Try using DISTINCT in case there are any duplicate rows.

**Comment by euan-maccoll** [comment]
> Try using DISTINCT in case there are any duplicate rows.

yeah that was it thanks
